### PR TITLE
Move PHPMYADMIN_VERSION to ENV. Pipe wget to tar to avoid using a temporary file. Fix a small typo in README.

### PR DESCRIPTION
**Pull request by echernyavskiy**
I found this Dockerfile really useful. Just wanted to contribute some minor clean-ups. Thanks.

### CODE REVIEW

**Comment by nazar-pc** [comment]
I like how elegantly you've changed it to avoid temporary file.
But I don't like reformatting everything, also there is no need for `PHPMYADMIN_VERSION` to be moved into `ENV`, since this will create one more useless layer and `PHPMYADMIN_VERSION` will be available in running container, while there is no need for that, you'll not likely even dig into container ever.

Can you revert changes except nice trick with tar extraction and typo in readme? I'd like to merge that, really nice to have.

**Comment by echernyavskiy** [comment]
@nazar-pc, fair enough, done

**Comment by nazar-pc** [comment]
Thank you very much!
Also you might be interesting in https://github.com/nazar-pc/docker-webserver - it radically simplifies management of standard PHP-FPM + MariaDB + Nginx + SSH (with git) stack as single service via Docker Compose, makes backups and restoration blazing fast and simple.

**Comment by echernyavskiy** [comment]
Sure thing.

https://github.com/nazar-pc/docker-webserver - definitely looks cool, a potential time-saver for me for sure!

**Pull request merged**
