### PR TITLE
Allow no password

### PR DESCRIPTION
**Pull request by francisbesset**

### CODE REVIEW

**Comment by nazar-pc** [comment]
Why do you need this?
Official containers require password to be set anyway, so it doesn't make sense, just potential security hole.

**Comment by francisbesset** [comment]
It is simple to setup a project in dev environment without password.
The official mysql image allow no password with [MYSQL_ALLOW_EMPTY_PASSWORD](https://hub.docker.com/_/mysql/#-mysql_allow_empty_password-) environment variable.

It is a security hole **only** if the mysql server allow no password!

**Comment by nazar-pc** [comment]
Well, it makes sense. But can you align all assignments and leave empty line as it was originally?
I do not like when someone reformats my code, please, respect it)
I'll merge PR right after that.

**Comment by francisbesset** [comment]
No problem, it's done!

Thank you very much.

**Comment by nazar-pc** [comment]
It is not really aligned, but I'll fix that myself.
Thanks for contribution!

**Pull request merged**
