### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by funkyfuture**
in regards to two patterns that i think are a good practice.

### CODE REVIEW

**Comment by nazar-pc** [comment]
I do not want to make `PHPMYADMIN_VERSION` a global environment variable, because it doesn't make sense and will not be used anywhere, causing one additional layer for nothing.
Files copying is good, didn't know it is possible to do it that way.

**Comment by funkyfuture** [comment]
i found it useful to figure out more precisely what is running in a container when inspecting it. it's kind of metadata. but yeah, most time it's useless.

**Comment by nazar-pc** [comment]
This image is intended to be used as always latest stable version of PhpMyAdmin.
If you want to know exact version of locally cached image without running it:

```
docker inspect nazarpc/phpmyadmin
```

You'll find exact command that was used to build image in `ContainerConfig > Cmd` key.

**Comment by funkyfuture** [comment]
i do not deny that it's a matter of gusto. :-)

imo it's more obvious as environment variable. also, it's a good pattern to place such information at the top of a `Dockerfile` to force the rebuild of all layers when a new version is build. certainly, in that particular case that wouldn't make a difference.

**Pull request closed without merging**
